#!/usr/bin/env bash
#
# This script will invite accounts to maintain repos within a
# single GitHub organization.
#
# In a codespace...
# 
#    1. Set GITHUB_TOKEN to a personal access token with scopes:
#
#        repo
#        write:org
#
#    2. Create a file tmp/data with the format below.
#       Use a single space to delimit username from reponame (not full URL).
#       Make sure the last line ends with a newline character.
#
#        username1 reponame1
#        username2 reponame2
#        ...
#
#    3. Run this command below replacing ORGNAME with the
#       GitHub organization name (not full URL) containing the repos.
#
#        scripts/grant-maintain-to-repos ORGNAME < tmp/data

set -eu -o pipefail

TARGET_GITHUB_ORG="${1}"

while read -r name repo
do
    echo "Add ${name} as maintainer to ${TARGET_GITHUB_ORG}/${repo}"
    echo "/repos/${TARGET_GITHUB_ORG}/${repo}/collaborators/${name}"
    gh api \
        --method PUT \
        -H "Accept: application/vnd.github+json" \
        -H "X-GitHub-Api-Version: 2022-11-28" \
        "/repos/${TARGET_GITHUB_ORG}/${repo}/collaborators/${name}" \
        -f "permission=maintain" \
        || true
    sleep 5
done
